version: '3'

services:
  app:
    build:
      context: ./
    image: "${DOCKER_REPOSITORY}/${PROJECT_NAME}:${TAG_VERSION}-${ENVIRONMENT:-development}"
    container_name: app-${ENVIRONMENT:-development}
    environment:
      - "NODE_ENV=${ENVIRONMENT:-development}"
      - "TAG_VERSION=${TAG_VERSION:-development}"

